LMS/routes/web.php
<?php
use Illuminate\Support\Facades\Route;

// Route::get('/', function () {
//     return view('welcome');
// });
Auth::routes();

Route::group([
    'namespace'=>'Frontend',
],function(){
    Route::get('/','ListBookController@index');
});
Route::group([
    'prefix'=>'admin',
    'namespace'=>'Admin',
    'middleware'=>'auth',

],function(){
    Route::get('/users', 'UserController@index')->name('admin.user.index');
});

Route::resource('/book', 'BookController');

LMS/app/Book.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Events\Registered;
// use Illuminate\Support\Facades\Request;
use Illuminate\Http\Request;

class Book extends Model
{
    public $fillable = [
        'name',
        'auth',
        'image',
    ];
    public static function addBook(Request $request){
        $books = new Book();
        foreach($books->fillable as $book){
            $books->{$book} = $request->get($book);
        }
        return $books->save();
        // dd($books);
    }
}

LMS/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

LMS/app/Http/Controllers/Admin/UserController.php
<?php

namespace App\Http\Controllers\Admin;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class UserController extends Controller
{
    function index(){
        return view('welcome');
    }
}

LMS/app/Http/Controllers/BookController.php
<?php

namespace App\Http\Controllers;

use App\Book;
use Illuminate\Http\Request;
// use Illuminate\Support\Facades\Request;

class BookController extends Controller
{
	public function index() {
		$data = Book::latest()->paginate(10);
		return view('layouts.pages.index', compact('data'))
			->with('i', (request()->input('page', 1) - 1) * 5);
    }
    
	public function create() {
		return view('layouts.pages.create');
	}
    
  public function store(Request $request) {
		$request->validate([
			'name' => 'required',
			'auth' => 'required',
			'image' => 'required|image|max:2048',
		]);

		$image = $request->file('image');

		$new_name = rand() . '.' . $image->getClientOriginalExtension();
		$image->move(public_path('images'), $new_name);
		$form_data = array(
			'name' => $request->name,
			'auth' => $request->auth,
			'image' => $new_name,
		);

		Book::create($form_data);
		// BooK::addBook($request);

		return redirect('book')->with('success', 'Data Added successfully.');
	}

	public function show($id) {
		$data = Book::findOrFail($id);
		return view('layouts.pages.view', compact('data'));
	}

	public function edit($id) {
		$data = Book::findOrFail($id);
		return view('layouts.pages.edit', compact('data'));
  }
    
	public function update(Request $request, $id) {
		$image_name = $request->hidden_image;
		$image = $request->file('image');
		if ($image != '') {
			$request->validate([
				'name' => 'required',
				'auth' => 'required',
				'image' => 'image|max:2048',
			]);
			$image_name = rand() . '.' . $image->getClientOriginalExtension();
			$image->move(public_path('images'), $image_name);
		} else {
			$request->validate([
				'name' => 'required',
				'auth' => 'required',
			]);
		}

		$form_data = array(
			'name' => $request->name,
			'auth' => $request->auth,
			'image' => $image_name,
		);

		Book::whereId($id)->update($form_data);
		return redirect('book')->with('success', 'Data is successfully updated');

    }
    
	public function destroy($id) {
		$data = Book::findOrFail($id);
		$path_image = public_path('/images/'.$data->image);
		if($path_image!=null){
			$data->delete();
			return redirect('book')->with('success', 'Data is successfully deleted');
		}
		else if($path_image==null){
			$data->delete();
			unlink($path_image);
			return redirect('book')->with('success', 'Data is successfully deleted');
		}else{
			return redirect('book')->with('success', 'Data is successfully deleted');
		}
	}
}

LMS/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

LMS/app/Http/Controllers/Frontend/ListBookController.php
<?php

namespace App\Http\Controllers\Frontend;

use App\Book;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ListBookController extends Controller
{
	public function index() {
		$data = Book::latest()->paginate(15);
		return view('welcome', compact('data'))
			->with('i', (request()->input('page', 1) - 1) * 5);
    }
}

LMS/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('welcome');
    }
}

LMS/resources/views/layouts/app.blade.php
 @include('layouts.header.head')
 @include('layouts.sidebar.sidebar')
    <main class="py-4">
        @yield('content')
    </main>
@include('layouts.footer.bottom')

LMS/resources/views/layouts/footer/bottom.blade.php
@include('layouts.footer.footer')
<!-- Bootstrap agency JavaScript -->
{{-- <script src="{{asset('vendor/jquery/jquery.min.js')}}"></script>
<script src="{{asset('vendor/bootstrap/js/bootstrap.bundle.min.js')}}"></script>
<script src="{{asset('vendor/jquery-easing/jquery.easing.min.js')}}"></script>
<script src="{{asset('s/jqBootstrapValidation.js')}}"></script>
<script src="{{asset('js/contact_me.js')}}"></script>
<script src="{{asset('js/agency.min.js')}}"></script> --}}

{{-- Bootstrap Admin JavaScript --}}
<script src="{{asset('plugins/bower_components/jquery/dist/jquery.min.js')}}"></script>
<script src="{{asset('bootstrap/dist/js/bootstrap.min.js')}}"></script>
<script src="{{asset('plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.js')}}"></script>
<script src="{{asset('js/jquery.slimscroll.js')}}"></script>
<script src="{{asset('js/waves.js')}}"></script>
<script src="{{asset('plugins/bower_components/waypoints/lib/jquery.waypoints.js')}}"></script>
<script src="{{asset('plugins/bower_components/counterup/jquery.counterup.min.js')}}"></script>
<script src="{{asset('plugins/bower_components/raphael/raphael-min.js')}}"></script>
<script src="{{asset('plugins/bower_components/morrisjs/morris.js')}}"></script>
<script src="{{asset('plugins/bower_components/chartist-js/dist/chartist.min.js')}}"></script>
<script src="{{asset('plugins/bower_components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.min.js')}}"></script>
<script src="{{asset('plugins/bower_components/moment/moment.js')}}"></script>
<script src="{{asset('plugins/bower_components/calendar/dist/fullcalendar.min.js')}}"></script>
<script src="{{asset('plugins/bower_components/calendar/dist/cal-init.js')}}"></script>
<script src="{{asset('js/custom.min.js')}}"></script>
<script src="{{asset('js/dashboard1.js')}}"></script>
<script src="{{asset('js/cbpFWTabs.js')}}"></script>
<script src="{{asset('text/javascript"')}}"></script>
</body></html>

LMS/resources/views/layouts/footer/footer.blade.php
<footer class="footer">
  <div class="container">
      <div class="row">
          <div class="col-md-4">
              <span class="copyright">Copyright &copy; Your Website 2019</span>
          </div>
          <div class="col-md-4">
              <ul class="list-inline social-buttons">
              <li class="list-inline-item">
                  <a href="#" class="btn btn-facebook btn-circle">
                  <i class="fa fa-refresh"></i>
                  </a>
              </li>
              <li class="list-inline-item">
                  <a href="#" class="btn btn-facebook btn-circle">
                  <i class="fa fa-facebook-f"></i>
                  </a>
              </li>
              <li class="list-inline-item">
                  <a href="#" class="btn btn-facebook btn-circle">
                  <i class="fa fa-linkedin"></i>
                  </a>
              </li>
              </ul>
          </div>
          <div class="col-md-4">
              <ul class="list-inline quicklinks">
              <li class="list-inline-item">
                  <a href="#">Privacy Policy</a>
              </li>
              <li class="list-inline-item">
                  <a href="#">Terms of Use</a>
              </li>
              </ul>
          </div>
      </div>
  </div>
</footer>

LMS/resources/views/layouts/header/head.blade.php
<!DOCTYPE html><html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name','Laravel') }}</title>
    {{-- style agency --}}
    {{-- <link href="{{ asset('vendor/bootstrap/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('vendor/fontawesome-free/css/all.min.css') }}" rel="stylesheet">
    <link href="{{ asset('css/agency.min.css') }}" rel="stylesheet"> --}}
    {{-- style admin --}}
    <link href="{{ asset('bootstrap/dist/css/bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/sidebar-nav/dist/sidebar-nav.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/toast-master/css/jquery.toast.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/morrisjs/morris.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/chartist-js/dist/chartist.min.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/chartist-plugin-tooltip-master/dist/chartist-plugin-tooltip.css') }}" rel="stylesheet">
    <link href="{{ asset('plugins/bower_components/calendar/dist/fullcalendar.css') }}" rel="stylesheet">
    <link href="{{ asset('css/animate.css') }}" rel="stylesheet">
    <link href="{{ asset('css/style.css') }}" rel="stylesheet">
    <link href="{{ asset('css/colors/blue-dark.css') }}" rel="stylesheet">
    {{-- <link href="{{ asset('') }}" rel="stylesheet"> --}}

</head><body class="bg-white">
<div style="margin-bottom:60px">
    @include('layouts.header.nav')
</div>

LMS/resources/views/layouts/pages/create.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
@if($errors->any())
	<div class="alert alert-danger">
		<ul>
			@foreach($errors->all() as $error)
			<li>{{ $error }}</li>
			@endforeach
		</ul>
	</div>
	@endif
	<div align="right">
		<a href="{{ route('book.index') }}" class="btn btn-sm btn-primary">Back</a>
	</div><br/>
	<form method="post" action="{{ route('book.store') }}" enctype="multipart/form-data">
		@csrf
		<div class="row">
			<div class="col">
				<div class="col-md-8">
					<input type="file" name="image" class="btn btn-light"/>
					{{-- <input type="text" name="image" class="form-control input-lg"> --}}
				</div>
			</div>
			<div class="col">
				<div style="text-align:left">
					<label for="">Name book</label><br/>
					<input type="text" name="name" class="form-control input-lg" />
					<label for="">Auth book</label><br/>
					<input type="text" name="auth" class="form-control input-lg" />
				</div>
				<input type="submit" name="add" class="btn btn-primary input-lg" value="Add" />
			</div>
		</div>
	</form>

@endsection

LMS/resources/views/layouts/pages/edit.blade.php
@extends('layouts.app')

@section('content')
<div align="right">
	<a href="{{ route('book.index') }}" class="btn btn-sm btn-primary">Back</a>
</div><br/>
<form method="post" action="{{ route('book.update', $data->id) }}" enctype="multipart/form-data">
	@csrf
	@method('PATCH')
	<div class="row">
		<div class="col-5">
			<div class="col-md-8">
				<img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-fluid rounded"/>
				<input type="hidden" name="hidden_image" value="{{ $data->image }}" />
				<input type="file" name="image" class="btn btn-light"/>
			</div>
		</div>
		<div class="col-7">
			<div style="text-align:left">
				<label for="">Name book</label><br/>
				<input class="form-control" name ="name" value="{{$data->name }}"/><br/>
				<label for="">Auth book</label><br/>
				<input class="form-control" name ="auth" value="{{$data->auth }}"/>
			</div>
			<input type="submit" name="edit" class="btn btn-info input-lg mt-3" value="Edit" />
		</div>
	</div>
</form>
@endsection

LMS/resources/views/layouts/pages/index.blade.php
@extends('layouts.app')
@section('content')
<div class="container">
  <div align="right">
    <a href="{{ route('book.create') }}" class="btn btn-primary">Add</a>
  </div>
  <br />
  @if ($message = Session::get('success'))
  <div class="alert alert-success">
    <p>{{ $message }}</p>
  </div>
  @endif
  <table class="table">
      <thead>
        <tr class="shadow-lg p-3 mb-5 bg-white rounded">
          <th scope="col" style="width:10%">N</th>
          <th scope="col" style="width:20%">Name</th>
          <th scope="col" style="width:20%">Author</th>
          <th scope="col" style="width:20%">Book Image</th>
          <th scope="col" style="text-align:center; width:30%">Action</th>
        </tr>
      </thead>
      <tbody>
        @foreach($data as $value)
        <tr class="shadow bg-white rounded">
          <td scope="row"></td>
          <td>{{ $value->name }}</td>
          <td>{{ $value->auth }}</td>
          <td>
            <img src="{{ URL::to('/') }}/images/{{ $value->image }}" class="img-thumbnail" style="height:30px; width:100%;"/>
          </td>
          <td style="text-align:center">
            <form action="{{ route('book.destroy', $value->id) }}" method="post">
            <a href="{{ route('book.show', $value->id) }}" class="btn btn-primary btn-sm">View</a>
            <a href="{{ route('book.edit', $value->id) }}" class="btn btn-warning btn-sm">Edit</a>
                @csrf
                @method('DELETE')
                <button type="submit" class="btn btn-danger btn-sm">Delete</button>
              </form>
          </td>
          </tr>
        @endforeach
      </tbody>
    </table>
    <div class="text-right">
      {!! $data->links() !!}
    </div>
</div>
@endsection

LMS/resources/views/layouts/pages/view.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div style="text-align:right; padding:10px 0px">
			<a href="{{ route('book.index') }}" class="btn btn-primary">Back</a>
		</div>
		<div class="jumbotron text-center">
			<div class="row">
				<div class="col-5">
					<img src="{{ URL::to('/') }}/images/{{ $data->image }}" class="img-fluid rounded"/>
				</div>
				<div class="col-7">
					<div style="text-align:left">
						<h3>First Name - {{ $data->name }} </h3>
						<h3>Last Name - {{ $data->auth }}</h3>
					</div>
				</div>
			</div>
		</div>
</div>
@endsection

LMS/resources/views/layouts/sidebar/sidebar.blade.php
<div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav slimscrollsidebar">
        <div class="sidebar-head">
            <h3><span class="fa-fw open-close"><i class="ti-menu hidden-xs"></i><i class="ti-close visible-xs"></i></span> <span class="hide-menu">Navigation</span></h3> </div>
        <ul class="nav" id="side-menu">
            <li class="user-pro">
                    @guest
                        <li>
                            <a href="{{ route('login') }}" class="waves-effect"><img src="plugins/images/favicon.png" alt="user-img" class="img-circle">
                                <span class="hide-menu"> {{ __('Login') }}<span class="fa arrow"></span></span>
                            </a>
                        </li>
                    @else
                        <li>
                            <a href="/" class="waves-effect"><img src="plugins/images/favicon.png" alt="user-img" class="img-circle">
                                <span class="hide-menu"> {{ Auth::user()->name }} <span class="fa arrow"></span></span>
                            </a>
                        </li>
                    @endguest
                
                <ul class="nav nav-second-level collapse" aria-expanded="false" style="height: 0px;">
                    <li><a href="javascript:void(0)"><i class="ti-user"></i> <span class="hide-menu">My Profile</span></a></li>
                    <li><a href="javascript:void(0)"><i class="ti-wallet"></i> <span class="hide-menu">My Balance</span></a></li>
                    <li><a href="javascript:void(0)"><i class="ti-email"></i> <span class="hide-menu">Inbox</span></a></li>
                    <li><a href="javascript:void(0)"><i class="ti-settings"></i> <span class="hide-menu">Account Setting</span></a></li>
                    <li><a href="javascript:void(0)"><i class="fa fa-power-off"></i> <span class="hide-menu">Logout</span></a></li>
                </ul>
            </li>
            <li> <a href="/" class="waves-effect"><i class="mdi mdi-format-color-fill fa-fw"></i> <span class="hide-menu">UI Elements<span class="fa arrow"></span> <span class="label label-rouded label-info pull-right">20</span> </span></a>
                <ul class="nav nav-second-level">
                    <li><a href="panels-wells.html"><i data-icon="&#xe026;" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Panels and Wells</span></a></li>
                    <li><a href="panel-ui-block.html"><i data-icon="&#xe025;" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Panels With BlockUI</span></a></li>
                    <li><a href="buttons.html"><i class="ti-layout-menu fa-fw"></i> <span class="hide-menu">Buttons</span></a></li>
                    <li><a href="sweatalert.html"><i class="ti-alert fa-fw"></i> <span class="hide-menu">Sweat alert</span></a></li>
                    <li><a href="typography.html"><i data-icon="k" class="linea-icon linea-software fa-fw"></i> <span class="hide-menu">Typography</span></a></li>
                    <li><a href="grid.html"><i data-icon="&#xe009;" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Grid</span></a></li>
                    <li><a href="tabs.html"><i  class="ti-layers fa-fw"></i> <span class="hide-menu">Tabs</span></a></li>
                    <li><a href="tab-stylish.html"><i class=" ti-layers-alt fa-fw"></i> <span class="hide-menu">Stylish Tabs</span></a></li>
                    <li><a href="modals.html"><i data-icon="&#xe026;" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Modals</span></a></li>
                    <li><a href="progressbars.html"><i class="ti-line-double fa-fw"></i> <span class="hide-menu">Progress Bars</span></a></li>
                    <li><a href="notification.html"><i class="ti-info-alt fa-fw"></i> <span class="hide-menu">Notifications</span></a></li>
                    <li><a href="carousel.html"><i class="ti-layout-slider fa-fw"></i> <span class="hide-menu">Carousel</span></a></li>
                    <li><a href="list-style.html"><i data-icon="&#xe00b;" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">List & Media object</span></a></li>
                    <li><a href="user-cards.html"><i class="ti-user fa-fw"></i> <span class="hide-menu">User Cards</span></a></li>
                    <li><a href="timeline.html"><i data-icon="/" class="linea-icon linea-basic fa-fw"></i> <span class="hide-menu">Timeline</span></a></li>
                    <li><a href="timeline-horizontal.html"><i class="ti-layout-list-thumb fa-fw"></i> <span class="hide-menu">Horizontal Timeline</span></a></li>
                    <li><a href="nestable.html"><i class="ti-layout-accordion-separated fa-fw"></i> <span class="hide-menu">Nesteble</span></a></li>
                    <li><a href="range-slider.html"><i class=" ti-layout-slider-alt fa-fw"></i> <span class="hide-menu">Range Slider</span></a></li>
                    <li><a href="tooltip-stylish.html"><i class="ti-comments-smiley fa-fw"></i> <span class="hide-menu">Stylish Tooltip</span></a></li>
                    <li><a href="bootstrap.html"><i class="ti-rocket fa-fw"></i> <span class="hide-menu">Bootstrap UI</span></a></li>
                </ul>
            </li>
            <li> <a href="/" class="waves-effect active"><i class="mdi mdi-table fa-fw"></i> <span class="hide-menu">Tables<span class="fa arrow"></span><span class="label label-rouded label-danger pull-right">9</span></span></a>
                <ul class="nav nav-second-level">
                    <li><a href="basic-table.html"><i class="fa-fw">B</i><span class="hide-menu">Basic Tables</span></a></li>
                    <li><a href="table-layouts.html"><i class="fa-fw">L</i><span class="hide-menu">Table Layouts</span></a></li>
                    <li><a href="data-table.html"><i class="fa-fw">D</i><span class="hide-menu">Data Table</span></a></li>
                    <li><a href="bootstrap-tables.html"><i class="fa-fw">B</i><span class="hide-menu">Bootstrap Tables</span></a></li>
                    <li><a href="responsive-tables.html"><i class="fa-fw">R</i><span class="hide-menu">Responsive Tables</span></a></li>
                    <li><a href="editable-tables.html"><i class="fa-fw">E</i><span class="hide-menu">Editable Tables</span></a></li>
                    <li><a href="foo-tables.html"><i class="fa-fw">F</i><span class="hide-menu">FooTables</span></a></li>
                    <li><a href="jsgrid.html"><i class="fa-fw">J</i><span class="hide-menu">JsGrid Tables</span></a></li>
                </ul>
            </li>
            <li> <a href="/" class="waves-effect"><i class="mdi mdi-chart-bar fa-fw"></i> <span class="hide-menu">Charts<span class="fa arrow"></span></span></a>
                <ul class="nav nav-second-level">
                    <li> <a href="flot.html"><i class="fa-fw">F</i><span class="hide-menu">Flot Charts</span></a> </li>
                    <li><a href="morris-chart.html"><i class="fa-fw">M</i><span class="hide-menu">Morris Chart</span></a></li>
                    <li><a href="chart-js.html"><i class="fa-fw">P</i><span class="hide-menu">Chart-js</span></a></li>
                    <li><a href="peity-chart.html"><i class="fa-fw">P</i><span class="hide-menu">Peity Charts</span></a></li>
                    <li><a href="chartist-js.html"><i class="fa-fw">C</i><span class="hide-menu">Chartist-js</span></a></li>
                    <li><a href="knob-chart.html"><i class="fa-fw">K</i><span class="hide-menu">Knob Charts</span></a></li>
                    <li><a href="sparkline-chart.html"><i class="fa-fw">S</i><span class="hide-menu">Sparkline charts</span></a></li>
                    <li><a href="extra-charts.html"><i class="fa-fw">E</i><span class="hide-menu">Extra Charts</span></a></li>
                </ul>
            </li>
            @guest
            {{-- <li><a href="/" class="waves-effect"><i class="mdi mdi-logout fa-fw"></i> <span class="hide-menu">Log out</span></a></li> --}}
            @else
            <li>
                <a href="{{ route('logout') }}" class="waves-effect"
                    onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();"><i class="mdi mdi-logout fa-fw"></i> <span class="hide-menu">Log out</span>
                </a>
                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                </form>
            </li>
            @endguest

            <li class="devider"></li>
            <li><a href="documentation.html" class="waves-effect"><i class="fa fa-circle-o text-danger"></i> <span class="hide-menu">Documentation</span></a></li>
            <li><a href="gallery.html" class="waves-effect"><i class="fa fa-circle-o text-info"></i> <span class="hide-menu">Gallery</span></a></li>
            <li><a href="faq.html" class="waves-effect"><i class="fa fa-circle-o text-success"></i> <span class="hide-menu">Faqs</span></a></li>
        </ul>
    </div>
</div>